### ISSUE TITLE
Screen Orientation for HealthyPi v4.4 Complete Kit – Slim Edition

### ISSUE THREAD

**Issue by williamsdoug** [Protocentral/protocentral_healthypi_v4#8]
Screen orientation for the Slim Edition is flipped out-of-the-box.  Recommend editing /boot/config.txt to include "lcd_rotate=2" in stock Slim Edition configuration

**Comment by protocentralashwin** [comment]
@williamsdoug Thank you for reporting this. We've fixed this in the new image for slim edition in Release v0.9.4 at https://github.com/Protocentral/protocentral_healthypi_v4/releases
